## Initial Test

In [3]:
import sys
sys.path.append("../")
import os

current_directory = os.getcwd()
print(current_directory)
from egta.symmetric_game import *
from egta.game import *
from egta.utils.eq_computation import *
from egta.utils.log_multimodal import *
from egta.utils.random_functions import *
from egta.utils.simplex_operations import *
from egta.process_data import *
import matplotlib.pyplot as plt
from egta.reductions.dpr import DPRGAME
import random
import itertools
from game_simulators_test import games


/Users/gabesmithline/Desktop/SRG/melo_project/marketsim/egta


In [4]:
# Generate and display the data
rps_profiles = games.generate_rps_25_player_data()


print(rps_profiles)
rps_data = rps_profiles

[[['agent_1', 'ROCK', 0], ['agent_2', 'ROCK', 0], ['agent_3', 'ROCK', 0], ['agent_4', 'ROCK', 0], ['agent_5', 'ROCK', 0], ['agent_6', 'ROCK', 0], ['agent_7', 'ROCK', 0], ['agent_8', 'ROCK', 0], ['agent_9', 'ROCK', 0], ['agent_10', 'ROCK', 0], ['agent_11', 'ROCK', 0], ['agent_12', 'ROCK', 0], ['agent_13', 'ROCK', 0], ['agent_14', 'ROCK', 0], ['agent_15', 'ROCK', 0], ['agent_16', 'ROCK', 0], ['agent_17', 'ROCK', 0], ['agent_18', 'ROCK', 0], ['agent_19', 'ROCK', 0], ['agent_20', 'ROCK', 0], ['agent_21', 'ROCK', 0], ['agent_22', 'ROCK', 0], ['agent_23', 'ROCK', 0], ['agent_24', 'ROCK', 0], ['agent_25', 'ROCK', 0]], [['agent_1', 'PAPER', 0], ['agent_2', 'PAPER', 0], ['agent_3', 'PAPER', 0], ['agent_4', 'PAPER', 0], ['agent_5', 'PAPER', 0], ['agent_6', 'PAPER', 0], ['agent_7', 'PAPER', 0], ['agent_8', 'PAPER', 0], ['agent_9', 'PAPER', 0], ['agent_10', 'PAPER', 0], ['agent_11', 'PAPER', 0], ['agent_12', 'PAPER', 0], ['agent_13', 'PAPER', 0], ['agent_14', 'PAPER', 0], ['agent_15', 'PAPER', 0],

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

rps_game = create_symmetric_game_from_data(rps_data, device=device)

[['agent_1', 'ROCK', 0], ['agent_2', 'ROCK', 0], ['agent_3', 'ROCK', 0], ['agent_4', 'ROCK', 0], ['agent_5', 'ROCK', 0], ['agent_6', 'ROCK', 0], ['agent_7', 'ROCK', 0], ['agent_8', 'ROCK', 0], ['agent_9', 'ROCK', 0], ['agent_10', 'ROCK', 0], ['agent_11', 'ROCK', 0], ['agent_12', 'ROCK', 0], ['agent_13', 'ROCK', 0], ['agent_14', 'ROCK', 0], ['agent_15', 'ROCK', 0], ['agent_16', 'ROCK', 0], ['agent_17', 'ROCK', 0], ['agent_18', 'ROCK', 0], ['agent_19', 'ROCK', 0], ['agent_20', 'ROCK', 0], ['agent_21', 'ROCK', 0], ['agent_22', 'ROCK', 0], ['agent_23', 'ROCK', 0], ['agent_24', 'ROCK', 0], ['agent_25', 'ROCK', 0]]
[['agent_1', 'PAPER', 0], ['agent_2', 'PAPER', 0], ['agent_3', 'PAPER', 0], ['agent_4', 'PAPER', 0], ['agent_5', 'PAPER', 0], ['agent_6', 'PAPER', 0], ['agent_7', 'PAPER', 0], ['agent_8', 'PAPER', 0], ['agent_9', 'PAPER', 0], ['agent_10', 'PAPER', 0], ['agent_11', 'PAPER', 0], ['agent_12', 'PAPER', 0], ['agent_13', 'PAPER', 0], ['agent_14', 'PAPER', 0], ['agent_15', 'PAPER', 0], [

/Users/gabesmithline/Desktop/SRG/melo_project/marketsim/egta/../egta/symmetric_game.py:53: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.config_table = torch.tensor(config_table, dtype=torch.float32, device=device)
/Users/gabesmithline/Desktop/SRG/melo_project/marketsim/egta/../egta/symmetric_game.py:54: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.payoff_table = torch.tensor(payoff_table, dtype=torch.float32, device=device)


In [6]:
rps_game.print_full_heuristic_payoff_table()

| Profile    |   PAPER Count |   ROCK Count |   SCISSORS Count | PAPER Payoff   | ROCK Payoff   | SCISSORS Payoff   |
|:-----------|--------------:|-------------:|-----------------:|:---------------|:--------------|:------------------|
| Profile 1  |             0 |           25 |                0 | N/A            | -21.9886      | N/A               |
| Profile 2  |            25 |            0 |                0 | -21.9886       | N/A           | N/A               |
| Profile 3  |             0 |            0 |               25 | N/A            | N/A           | -21.9886          |
| Profile 4  |             5 |           15 |                5 | -22.0000       | -22.0000      | -22.0000          |
| Profile 5  |            15 |            5 |                5 | -22.0000       | -22.0000      | -22.0000          |
| Profile 6  |             5 |            5 |               15 | -22.0000       | -22.0000      | -22.0000          |
| Profile 7  |            10 |           10 |           

In [7]:
'''
new_game_data = [
  # Round 1 - Everyone plays ROCK (tie)
  [
    ['agent_1', 'ROCK', 0],
    ['agent_2', 'ROCK', 0],
    ['agent_3', 'ROCK', 0],
    ['agent_4', 'ROCK', 0],
    ['agent_5', 'ROCK', 0],
    ['agent_6', 'ROCK', 0],
    ['agent_7', 'ROCK', 0],
    ['agent_8', 'ROCK', 0],
    ['agent_9', 'ROCK', 0],
    ['agent_10', 'ROCK', 0],
    ['agent_11', 'ROCK', 0],
    ['agent_12', 'ROCK', 0],
    ['agent_13', 'ROCK', 0],
    ['agent_14', 'ROCK', 0],
    ['agent_15', 'ROCK', 0],
    ['agent_16', 'ROCK', 0],
    ['agent_17', 'ROCK', 0],
    ['agent_18', 'ROCK', 0],
    ['agent_19', 'ROCK', 0],
    ['agent_20', 'ROCK', 0],
    ['agent_21', 'ROCK', 0],
    ['agent_22', 'ROCK', 0],
    ['agent_23', 'ROCK', 0],
    ['agent_24', 'ROCK', 0],
    ['agent_25', 'ROCK', 0]
  ],
  
  # Round 2 - Everyone plays PAPER (tie)
  [
    ['agent_1', 'PAPER', 0],
    ['agent_2', 'PAPER', 0],
    ['agent_3', 'PAPER', 0],
    ['agent_4', 'PAPER', 0],
    ['agent_5', 'PAPER', 0],
    ['agent_6', 'PAPER', 0],
    ['agent_7', 'PAPER', 0],
    ['agent_8', 'PAPER', 0],
    ['agent_9', 'PAPER', 0],
    ['agent_10', 'PAPER', 0],
    ['agent_11', 'PAPER', 0],
    ['agent_12', 'PAPER', 0],
    ['agent_13', 'PAPER', 0],
    ['agent_14', 'PAPER', 0],
    ['agent_15', 'PAPER', 0],
    ['agent_16', 'PAPER', 0],
    ['agent_17', 'PAPER', 0],
    ['agent_18', 'PAPER', 0],
    ['agent_19', 'PAPER', 0],
    ['agent_20', 'PAPER', 0],
    ['agent_21', 'PAPER', 0],
    ['agent_22', 'PAPER', 0],
    ['agent_23', 'PAPER', 0],
    ['agent_24', 'PAPER', 0],
    ['agent_25', 'PAPER', 0]
  ],
  
  # Round 3 - Mixed plays
  [
    ['agent_1', 'ROCK', 5],      # Group 1: Rock (wins against scissors)
    ['agent_2', 'ROCK', 5],
    ['agent_3', 'ROCK', 5],
    ['agent_4', 'ROCK', 5],
    ['agent_5', 'ROCK', 5],
    ['agent_6', 'ROCK', 5],
    ['agent_7', 'ROCK', 5],
    ['agent_8', 'ROCK', 5],
    ['agent_9', 'PAPER', 5],     # Group 2: Paper (wins against rock)
    ['agent_10', 'PAPER', 5],
    ['agent_11', 'PAPER', 5],
    ['agent_12', 'PAPER', 5],
    ['agent_13', 'PAPER', 5],
    ['agent_14', 'PAPER', 5],
    ['agent_15', 'PAPER', 5],
    ['agent_16', 'PAPER', 5],
    ['agent_17', 'SCISSORS', -10], # Group 3: Scissors (loses to rock)
    ['agent_18', 'SCISSORS', -10],
    ['agent_19', 'SCISSORS', -10],
    ['agent_20', 'SCISSORS', -10],
    ['agent_21', 'SCISSORS', -10],
    ['agent_22', 'SCISSORS', -10],
    ['agent_23', 'SCISSORS', -10],
    ['agent_24', 'SCISSORS', -10],
    ['agent_25', 'SCISSORS', -10]
  ],
  
  # Round 4 - Another mixed round
  [
    ['agent_1', 'ROCK', 10],     # Group 1: Rock (wins against scissors)
    ['agent_2', 'ROCK', 10],
    ['agent_3', 'ROCK', 10],
    ['agent_4', 'ROCK', 10],
    ['agent_5', 'ROCK', 10],
    ['agent_6', 'PAPER', -10],   # Group 2: Paper (loses to scissors)
    ['agent_7', 'PAPER', -10],
    ['agent_8', 'PAPER', -10],
    ['agent_9', 'PAPER', -10],
    ['agent_10', 'PAPER', -10],
    ['agent_11', 'PAPER', -10],
    ['agent_12', 'PAPER', -10],
    ['agent_13', 'PAPER', -10],
    ['agent_14', 'SCISSORS', 0], # Group 3: Scissors (neutral - wins and losses balance)
    ['agent_15', 'SCISSORS', 0],
    ['agent_16', 'SCISSORS', 0],
    ['agent_17', 'SCISSORS', 0],
    ['agent_18', 'SCISSORS', 0],
    ['agent_19', 'SCISSORS', 0],
    ['agent_20', 'SCISSORS', 0],
    ['agent_21', 'SCISSORS', 0],
    ['agent_22', 'SCISSORS', 0],
    ['agent_23', 'SCISSORS', 0],
    ['agent_24', 'SCISSORS', 0],
    ['agent_25', 'SCISSORS', 0]
  ],
  
  # Round 5 - Introducing LIZARD and SPOCK
  [
    ['agent_1', 'ROCK', 15],     # Group 1: Rock (crushes lizard)
    ['agent_2', 'ROCK', 15],
    ['agent_3', 'ROCK', 15],
    ['agent_4', 'ROCK', 15],
    ['agent_5', 'ROCK', 15],
    ['agent_6', 'PAPER', -15],   # Group 2: Paper (eaten by lizard)
    ['agent_7', 'PAPER', -15],
    ['agent_8', 'PAPER', -15],
    ['agent_9', 'PAPER', -15],
    ['agent_10', 'PAPER', -15],
    ['agent_11', 'SCISSORS', 5], # Group 3: Scissors (cuts lizard)
    ['agent_12', 'SCISSORS', 5],
    ['agent_13', 'SCISSORS', 5],
    ['agent_14', 'SCISSORS', 5],
    ['agent_15', 'SCISSORS', 5],
    ['agent_16', 'LIZARD', -5],  # Group 4: Lizard (crushed by rock, eats paper)
    ['agent_17', 'LIZARD', -5],
    ['agent_18', 'LIZARD', -5],
    ['agent_19', 'LIZARD', -5],
    ['agent_20', 'LIZARD', -5],
    ['agent_21', 'SPOCK', 0],    # Group 5: Spock (vaporizes rock, smashed by lizard)
    ['agent_22', 'SPOCK', 0],
    ['agent_23', 'SPOCK', 0],
    ['agent_24', 'SPOCK', 0],
    ['agent_25', 'SPOCK', 0]
  ]
]

rps_game.update_with_new_data(new_game_data)
rps_game.print_full_heuristic_payoff_table()
'''

"\nnew_game_data = [\n  # Round 1 - Everyone plays ROCK (tie)\n  [\n    ['agent_1', 'ROCK', 0],\n    ['agent_2', 'ROCK', 0],\n    ['agent_3', 'ROCK', 0],\n    ['agent_4', 'ROCK', 0],\n    ['agent_5', 'ROCK', 0],\n    ['agent_6', 'ROCK', 0],\n    ['agent_7', 'ROCK', 0],\n    ['agent_8', 'ROCK', 0],\n    ['agent_9', 'ROCK', 0],\n    ['agent_10', 'ROCK', 0],\n    ['agent_11', 'ROCK', 0],\n    ['agent_12', 'ROCK', 0],\n    ['agent_13', 'ROCK', 0],\n    ['agent_14', 'ROCK', 0],\n    ['agent_15', 'ROCK', 0],\n    ['agent_16', 'ROCK', 0],\n    ['agent_17', 'ROCK', 0],\n    ['agent_18', 'ROCK', 0],\n    ['agent_19', 'ROCK', 0],\n    ['agent_20', 'ROCK', 0],\n    ['agent_21', 'ROCK', 0],\n    ['agent_22', 'ROCK', 0],\n    ['agent_23', 'ROCK', 0],\n    ['agent_24', 'ROCK', 0],\n    ['agent_25', 'ROCK', 0]\n  ],\n  \n  # Round 2 - Everyone plays PAPER (tie)\n  [\n    ['agent_1', 'PAPER', 0],\n    ['agent_2', 'PAPER', 0],\n    ['agent_3', 'PAPER', 0],\n    ['agent_4', 'PAPER', 0],\n    ['agent_5',

In [8]:
# Create symmetric game from the data
#device = "cuda" if torch.cuda.is_available() else "cpu"
#rps_game = create_symmetric_game_from_data(rps_data, device=device)
print(rps_game.num_players)
print(rps_game.num_actions)
print(rps_game.strategy_names)
print(rps_game.config_table)
print(rps_game.payoff_table)
print(rps_game.print_full_heuristic_payoff_table())
print(f"Created RPS game with {rps_game.num_players} players and {rps_game.num_actions} strategies")
print(f"Strategy names: {rps_game.strategy_names}")

#find Nash equilibrium using replicator dynamics
iters = 1000

#generate random mixture
random_mixture = torch.rand(rps_game.num_actions, device=rps_game.device)
random_mixture = simplex_normalize(random_mixture)
print(f"Starting random mixture: {random_mixture}")

#run fictitious play
#NOTE: very sensitive to step size, and the initial mixture
#FP works, gradient descent works, rd works
#Not better response does not work?

'''
NOTE:, very sensitive to step size, and the initial mixture, and other hyperparameters
'''
best_mixture, eq_candidates, regrets = find_equilibria(rps_game, logging=True)
print(eq_candidates)
print("\nNash Equilibrium:")

for i, strat in enumerate(rps_game.strategy_names):
    print(f"{strat}: {best_mixture[i].item():.4f}")
print(best_mixture)
#print(f"\nMaximum deviation from uniform: {torch.max(torch.abs(eq_mixture - 1/rps_game.num_actions)).item():.6f}")



regret = rps_game.regret(best_mixture)
print(best_mixture)
print(f"Regret at equilibrium: {regret.item():.6f}")

'''
# Plot convergence history
plt.figure(figsize=(10, 6))
for i, strat in enumerate(rps_game.strategy_names):
    plt.plot(eq_history[i, :].cpu().numpy(), label=strat)
plt.xlabel("Iteration")
plt.ylabel("Strategy Probability")
plt.legend()
plt.title("Replicator Dynamics Convergence")
plt.grid(True, alpha=0.3)
plt.show()

# Plot regret over iterations
regrets = torch.zeros(iters+1, device=device)
for i in range(iters+1):
    regrets[i] = rps_game.regret(eq_history[:, i])

plt.figure(figsize=(10, 4))
plt.plot(regrets.cpu().numpy())
plt.xlabel("Iteration")
plt.ylabel("Regret")
plt.title("Regret Convergence")
plt.yscale('log')
plt.grid(True, alpha=0.3)
plt.show()
'''






25
3
['PAPER', 'ROCK', 'SCISSORS']
tensor([[ 0., 25.,  0.],
        [25.,  0.,  0.],
        [ 0.,  0., 25.],
        [ 5., 15.,  5.],
        [15.,  5.,  5.],
        [ 5.,  5., 15.],
        [10., 10.,  5.],
        [ 5., 10., 10.],
        [10.,  5., 10.],
        [ 8.,  8.,  9.],
        [ 8.,  9.,  8.],
        [ 9.,  8.,  8.],
        [ 2.,  2., 21.],
        [ 3., 20.,  2.],
        [20.,  3.,  2.],
        [ 3.,  2., 20.],
        [ 1., 23.,  1.],
        [23.,  1.,  1.],
        [ 1.,  1., 23.],
        [12., 13.,  0.],
        [ 0., 13., 12.],
        [13.,  0., 12.],
        [ 7., 12.,  6.],
        [12.,  6.,  7.],
        [ 6.,  7., 12.],
        [ 7.,  9.,  9.],
        [ 9.,  7.,  9.],
        [ 9.,  9.,  7.],
        [ 9., 15.,  1.],
        [15.,  1.,  9.],
        [ 1.,  9., 15.],
        [ 4., 17.,  4.],
        [17.,  4.,  4.],
        [ 4.,  4., 17.],
        [ 2., 21.,  2.],
        [21.,  2.,  2.],
        [ 7., 11.,  7.],
        [11.,  7.,  7.],
        [ 7.,  

'\n# Plot convergence history\nplt.figure(figsize=(10, 6))\nfor i, strat in enumerate(rps_game.strategy_names):\n    plt.plot(eq_history[i, :].cpu().numpy(), label=strat)\nplt.xlabel("Iteration")\nplt.ylabel("Strategy Probability")\nplt.legend()\nplt.title("Replicator Dynamics Convergence")\nplt.grid(True, alpha=0.3)\nplt.show()\n\n# Plot regret over iterations\nregrets = torch.zeros(iters+1, device=device)\nfor i in range(iters+1):\n    regrets[i] = rps_game.regret(eq_history[:, i])\n\nplt.figure(figsize=(10, 4))\nplt.plot(regrets.cpu().numpy())\nplt.xlabel("Iteration")\nplt.ylabel("Regret")\nplt.title("Regret Convergence")\nplt.yscale(\'log\')\nplt.grid(True, alpha=0.3)\nplt.show()\n'

## Construct DPR Game From Symmetric Game

In [12]:
dpr_rps_game = DPRGAME(rps_game, 5) 

#solve dpr_game 
#game, mix, iters=1000, offset=0
best_mixture, eq_candidates, regrets = find_equilibria(dpr_rps_game, logging=True)
print(eq_candidates)
print("\nNash Equilibrium:")

for i, strat in enumerate(rps_game.strategy_names):
    print(f"{strat}: {best_mixture[i].item():.4f}")
print(best_mixture)
#print(f"\nMaximum deviation from uniform: {torch.max(torch.abs(eq_mixture - 1/rps_game.num_actions)).item():.6f}")



regret = dpr_rps_game.regret(best_mixture)
print(best_mixture)
print(f"Regret at equilibrium: {regret.item():.6f}")

Found profile: 24
Found profile: 19
Found profile: 0
Found profile: 23
Found profile: 1
Found profile: 22
Found profile: 20
Found profile: 21
Found profile: 2
tensor([[0.3364, 0.3364, 0.3364, 0.3364, 0.3364, 0.3364, 0.3364, 0.3364, 0.3364,
         0.3364],
        [0.3387, 0.3387, 0.3387, 0.3387, 0.3387, 0.3387, 0.3387, 0.3387, 0.3387,
         0.3387],
        [0.3249, 0.3249, 0.3249, 0.3249, 0.3249, 0.3249, 0.3249, 0.3249, 0.3249,
         0.3249]])

Nash Equilibrium:
PAPER: 0.3364
ROCK: 0.3387
SCISSORS: 0.3249
tensor([0.3364, 0.3387, 0.3249])
tensor([0.3364, 0.3387, 0.3249])
Regret at equilibrium: 0.000000


/Users/gabesmithline/Desktop/SRG/melo_project/marketsim/egta/../egta/reductions/dpr.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  config_table[i] = torch.tensor(conf, device=self.device)
/Users/gabesmithline/Desktop/SRG/melo_project/marketsim/egta/../egta/symmetric_game.py:53: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.config_table = torch.tensor(config_table, dtype=torch.float32, device=device)
/Users/gabesmithline/Desktop/SRG/melo_project/marketsim/egta/../egta/symmetric_game.py:54: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTens

In [13]:
dpr_rps_game.print_full_heuristic_payoff_table()

| Profile    |   PAPER Count |   ROCK Count |   SCISSORS Count | PAPER Payoff   | ROCK Payoff   | SCISSORS Payoff   |
|:-----------|--------------:|-------------:|-----------------:|:---------------|:--------------|:------------------|
| Profile 1  |             4 |            0 |                1 | 0.0796         | N/A           | 0.0994            |
| Profile 2  |             1 |            2 |                2 | 0.0129         | 0.0212        | 0.0122            |
| Profile 3  |             2 |            3 |                0 | 0.0512         | 0.0227        | N/A               |
| Profile 4  |             1 |            0 |                4 | 0.0078         | N/A           | 0.0835            |
| Profile 5  |             0 |            4 |                1 | N/A            | 0.0876        | 0.0082            |
| Profile 6  |             1 |            1 |                3 | 0.0120         | 0.0230        | 0.0211            |
| Profile 7  |             0 |            5 |           